apiVersion: v1
kind: Pod
metadata:
  name: chat
spec:
  containers:
    - name: chat
      image: riyadennis/chat
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
