auth:
  security: qBAbLFsUqEq85IEzlkebtqKde0Pybyw7ddzV8Gnk13JD3d1qMo1vBilrCV3j7B9k
  providers:
    - name: google
      client: ${{ secrets.google_client }}
      secret: ${{ secrets.google_secret }}
      url: http://localhost:8080/auth/callback/google/
    - name: facebook
      client: ${{ secrets.facebook_client }}
      secret: ${{ secrets.facebook_secret }}
      url: http://localhost:8080/auth/callback/facebook/
template_path: templates