auth:
  security-key: AIzaSyBo1V1NqpsCmuLRhe7RTvGR2Njb9kjkjj3oFOqM99ioiL
  providers:
    - name: google
      client: 620226514233-f2lssbjdrvfnmjh4svofs5qm51kpqtot.apps.googleusercontent.com
      secret: qBiynOAr9qZsfhAJbXNnCWdp
      url: http://localhost:8080/auth/callback/google
    - name: facebook
      client: 620226514233-f2lssbjdrvfnmjh4svofs5qm51kpqtot.apps.googleusercontent.com
      secret: qBiynOAr9qZsfhAJbXNnCWdp
      url: http://localhost:8080/auth/callback/google